apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-traefik-config
  namespace: ingress-system
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      fields:
        index: side-app
        pod_name: '${pod_name}'
        pod_ip: '${pod_ip}'
        node_ip: '${node_ip}'
        node_name: '${node_name}'
        labels_app: 'traefik'
        index_prefix: "k8s-traefik-"
        pipeline: 'traefik_log_pipline'
      paths:
        - "/usr/share/filebeat/app/logs/*.log"
    setup.kibana:
      host: "kibana:5601"
    logging.metrics.enabled: false
    processors:
      - drop_fields:
          #删除的多余字段
          fields: ["start_time","host", "tags", "ecs",  "prospector", "agent", "input", "beat", "offset"]
          ignore_missing: true
    output.kafka:
      version: 1.1.1
      enabled: true
      hosts: ["log-kafka-brokers-svc.monitoring.svc.cluster.local:9092"]
      topic: filebeat_log
      required_acks: 1
      compression: none
      max_message_bytes: 1000000