kind: Service
apiVersion: v1
metadata:
  name: log-es-svc
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
---
kind: Endpoints
apiVersion: v1
metadata:
  name: log-es-svc
  namespace: monitoring
subsets:
  - addresses:
      - ip: 10.6.16.8
    ports:
      - port: 9200
