kind: Service
apiVersion: v1
metadata:
  name: log-kafka-brokers-svc
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
---
kind: Endpoints
apiVersion: v1
metadata:
  name: log-kafka-brokers-svc
  namespace: monitoring
subsets:
  - addresses:
      - ip: 10.6.16.48
    ports:
      - port: 9092
