kind: Service
apiVersion: v1
metadata:
  name: operation-redis-svc
  namespace: ysw-server
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
---
kind: Endpoints
apiVersion: v1
metadata:
  name: operation-redis-svc
  namespace: ysw-server
subsets:
  - addresses:
      - ip: 10.6.0.8
    ports:
      - port: 6379
