kind: Service
apiVersion: v1
metadata:
  name: operation-mysql-svc
  namespace: ysw-server
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
---
kind: Endpoints
apiVersion: v1
metadata:
  name: operation-mysql-svc
  namespace: ysw-server
subsets:
  - addresses:
      - ip: 10.6.0.13
    ports:
      - port: 3306
