apiVersion: v1
kind: ConfigMap
metadata:
  name: fb-config-java
data:
  filebeat.yml: |
    logging.level: info
    filebeat.config.modules:
      path: /usr/share/filebeat/modules.d/*.yml
      reload.enabled: false
      reload.period: 10s

    filebeat.config.inputs:
      path: /usr/share/filebeat/conf.d/*.yml
      reload.enabled: false
      reload.period: 10s

    filebeat.inputs:
    - type: log
      enabled: true
      fields:
        index: side-app
        pod_name: '${pod_name}'
        pod_ip: '${pod_ip}'
        node_ip: '${node_ip}'
        node_name: '${node_name}'
        labels_app: '${labels_app}'
        index_prefix: "k8s-${labels_app}-"
        pipeline: java_log_pipline
      paths:
        - "/usr/share/filebeat/app/logs/*.log"
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after
      multiline.timeout: 30
    setup.kibana:
      host: "kibana.monitoring.svc.cluster.local:5601"
    logging.metrics.enabled: false
    processors:
      - drop_fields:
          #删除的多余字段
          fields: []#["start_time","host", "tags", "ecs",  "prospector", "agent", "input", "beat", "offset","fields.index"]
          ignore_missing: true
    output.kafka:
      version: 1.1.1
      enabled: true
      hosts: ["log-kafka-brokers-svc.monitoring.svc.cluster.local:9092"]
      topic: filebeat_log
      required_acks: 1
      max_message_bytes: 1000000
      compression: none

