kind: Service
apiVersion: v1
metadata:
  name: jenkins-svc
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
---
kind: Endpoints
apiVersion: v1
metadata:
  name: jenkins-svc
  namespace: monitoring
subsets:
  - addresses:
      - ip: 192.168.64.183
    ports:
      - port: 8080
